### ISSUE TITLE
work-in-progress

### ISSUE THREAD

**Issue by iancrowther** [OpenBookPrices/country-data#21]
Hi there,

I took a look at the WIP to see if I could notch it off the list and it raised a q's.

How can you have a dialing code for a region?  
Are the codes correct? I could not correlate the data to any meaningful source.  Could you provide this?

There are also also a few regions missing.  

Happy to contrib if I can get some data.

**Comment by iancrowther** [comment]
@evdb

**Comment by evdb** [comment]
The calling codes came originally from http://en.wikipedia.org/wiki/List_of_country_calling_codes. I'm not sure what a region code would be either, but it was there is the data so I added it to the `data/work-in-progress/calling-codes.csv` file so that they'd be represented in some way in this project.

**Comment by iancrowther** [comment]
if we can't get an accurate data source, id be tempted to remove.  no data is surely better than bad data?

Either way can we manage this issue as it does not appear to have a resolution :-)

**Comment by evdb** [comment]
At the moment those calling codes are just in that file, not actually in the data that the module exposes. As such surely it is fine to leave it as it is? Or am I misunderstanding your concern?

**Comment by iancrowther** [comment]
yeah a bit, my concern is having issues linger.  this issue has no resolution as call codes can't be verified.

so how to progress, close the issue and just leave the folder? remove the folder?

i dont actually care if the folder stays, im just keen to keep the issue list valid or actionable

**Comment by evdb** [comment]
The folder is just there for reference - the data is not actually exposed via the module. I like to keep bad data around in this way so that they can be found, if needed, when searching through the code base. Closing this issue, please reopen if you don't agree.

**Comment by iancrowther** [comment]
lgtm.. ty
