### ISSUE TITLE
Data about Vietnam is non-existent

### ISSUE THREAD

**Issue by gajus** [OpenBookPrices/country-data#27]
http://en.wikipedia.org/wiki/Vietnam

**Comment by evdb** [comment]
It is in [countries.csv line 252](https://github.com/OpenBookPrices/country-data/blob/master/data/countries.csv#L252), but the name it has in "Viet Nam" (as per the ISO3661 entry on [wikipedia](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#VN)).

Perhaps this is supporting evidence for the need for #26 to be addressed? :)
