### ISSUE TITLE
Some corrections

### ISSUE THREAD

**Issue by cespon** [OpenBookPrices/country-data#34]
Some observations to improve [countries.json](https://github.com/OpenBookPrices/country-data/blob/master/data/countries.json):

- `alpha2: "IC"` and `alpha2: "EA"` are not countries. Canary Islands, Ceuta and Melilla are [Spain's regions](http://en.wikipedia.org/wiki/Spain).
- `alpha2: "GB"` and `alpha2: "UK"` are the same country. The correct [ISO Code](http://en.wikipedia.org/wiki/ISO_3166) is `GB`.
- `alpha2: "EU"` isn't a country (it's a politico-economic union of [28 countries](http://en.wikipedia.org/wiki/European_Union)).

**Comment by evdb** [comment]
These are all marked with a status of `reserved`.

I think I'll leave them in for now. What actually constitutes a country is a pretty difficult question. See [Åland](https://en.wikipedia.org/wiki/%C3%85land_Islands) for a great example :)
