### ISSUE TITLE
How to distinguish between Currency and Currency Type

### ISSUE THREAD

**Issue by uttamjaiswal86** [OpenBookPrices/country-data#46]
Hi All,

First of all thanks for the country data which you made it . I have some css requirement which i am not able to distinguish here. My issue is as below.

I am basically from INDIA and which I saw my country has INR as currency and Currency Type is Rupees. So like Database should have this as well.

Country :- INDIA , Currency :- INR, Currency Type :- Rupee
Country :- BANGALADESH Currency :- Currency :- BDT Type :- TAKA
Country :- Pakistan Currency :- PKR, Currency Type :- Rupee 

Please advise. 

Thanks

**Comment by evdb** [comment]
I don't think that this is a general enough use case to make it into the main codebase, sorry. You could always add the `currency type` field yourself to the currencies that need it just after loading the `country-data` module - they are just data structures held in memory. Or you could wrap the module in one of your own that adds the entries before returning the data, then you'd be sure that they are always there.

Please reopen if you feel I'm missing something.
