### ISSUE TITLE
alpha3 missing for United Kingdom

### ISSUE THREAD

**Issue by bebraw** [OpenBookPrices/country-data#5]
That should be GBR.

**Comment by bryandowning** [comment]
@evdb

Given this:
> The European Commission generally uses ISO 3166-1 alpha-2 codes with two exceptions: EL (not GR) is used to represent Greece, and UK (not GB) is used to represent the United Kingdom.
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Imperfect_implementations

...it would be nice to have GBR listed as the alpha3 for UK.

I'm using this package to map alpha2 country codes to alpha3 codes, and I'm getting empty string returned when the input is `UK`.
