### ISSUE TITLE
Alpha3 ATB begins with space

### ISSUE THREAD

**Issue by dbellavista** [OpenBookPrices/country-data#56]
In https://github.com/OpenBookPrices/country-data/blob/master/data/countries.json#L526 alpha3 should be `"ATB"` and not `" ATB"`

**Comment by evdb** [comment]
Closed in c68268b67156e6503074bf19adfbe619a275d61a

**Comment by evdb** [comment]
Just released v0.0.26 now with fix in it - thanks for reporting :)
