### ISSUE TITLE
Usage with webpack?

### ISSUE THREAD

**Issue by cslashnet** [OpenBookPrices/country-data#57]
Hi,
I am not getting how to use it with webpack&c:

import CountryData from 'country-data';
CountryData.lookup.countries({currencies: 'EUR'});

generates:
Uncaught (in promise) TypeError: data.filter is not a function(…)

Am I doing something wrong?

**Comment by evdb** [comment]
I don't use webpack so can't comment. Anyone else have any observations?

**Comment by dadambickford** [comment]
Same issue. Throwing a debugger in the script where I'm importing 'country-data', `countryData.countries.all` returns an empty object.

**Comment by freen** [comment]
Same issue.

```
import countryData from 'country-data';
console.log(countryData);
```
![screen shot 2016-08-04 at 16 45 38](https://cloud.githubusercontent.com/assets/1816457/17406240/f03c368e-5a62-11e6-86a6-262174b646c8.png)

**Comment by luxflux** [comment]
I had to install and configure `json-loader` in webpack to fix this:

```bash
npm install json-loader --save-dev
```

```javascript
// webpack.config.js

// ...
   loaders: [
      // other loaders
      { test: /\.json$/, loader: 'json' },
  ],
// ...

**Comment by evdb** [comment]
Thank you @luxflux - would adding the `webpack.config.js` file to `country-data` be a way to close this issue?

**Comment by luxflux** [comment]
Hm, I'm pretty new to this stuff as well... But I don't think adding `webpack.config.js` would help as this is a config which is project specific and won't automagically be searched in the dependencies.
IMHO mentioning this in the README would be sufficient.

**Comment by evdb** [comment]
Thanks for the input. Notes about webpack added to README and code now on NPM as v0.0.28
