### ISSUE TITLE
countries.SK returning Sikkim instead of Slovakia since 0.0.25

### ISSUE THREAD

**Issue by silverwind** [OpenBookPrices/country-data#62]
Since 0.0.25, the 2-digit ISO code `SK` had changed from Slovakia to Sikkim:

#### 0.0.24
```
> require('country-data').countries.SK.name
'Slovakia'
```
#### 0.0.25
```
> require('country-data').countries.SK.name
'Sikkim'
```

According to [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#SK), SK still belongs to Slovakia and SK was actually assigned to Sikkim before 1993. Maybe this change was unintentional?

**Comment by silverwind** [comment]
Same issue with `BY`: Previously `Byelorussian SSR`, should now be `Belarus` [ref](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#BY). It looks like https://github.com/OpenBookPrices/country-data/commit/b3cbdabd46be67c7f9a2e4083516507df68a6dd5 introduced a few duplicate 2-character codes.

**Comment by mattvadrise** [comment]
It's important to have this historical data on previous country code assignments.  This means that there are duplicate 2 character codes but they can be distinguished by the the status attribute.  "Status": "assigned" indicates the current standard.

**Comment by silverwind** [comment]
Yes, I agree historical data is valuable, but the lookup that happens on `countries.<CC>` should return the currently assigned country when multiple assignments are found.

**Comment by mattvadrise** [comment]
Ah, yes I see your point.  I agree.

**Comment by evdb** [comment]
Sorry about this bug, thank you for spotting it. v0.0.31 (now on NPM) has fixed it. :)
